language: node_js
node_js:
  - '0.10'
  - "0.12"
  - "v4"
  - "v5"
  - "v6"
  - "v7"
  - "v8"
  - "v9"
  - "v10"
notifications:
  email: false
install:
  - npm install
script:
  - npm run test
  - npm run test-browser
